# Generated by Django 3.0.6 on 2020-05-25 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ID_Info',
            new_name='IdInfo',
        ),
    ]
